# Generated by Django 5.2.5 on 2025-08-12 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('tipoAlojamiento', models.CharField(max_length=50, null=True)),
                ('ubicacion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipoHabitacion', models.CharField(max_length=50)),
                ('camasSimples', models.IntegerField()),
                ('camasDobles', models.IntegerField()),
                ('bañoPrivado', models.BooleanField()),
                ('cocina', models.BooleanField()),
                ('desayuno', models.BooleanField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alojamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.alojamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantNoches', models.IntegerField()),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('checkIn', models.DateTimeField()),
                ('checkOut', models.DateTimeField()),
                ('nombreHuesped', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField()),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodoDePago', models.CharField(max_length=50)),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.reserva')),
            ],
        ),
    ]
