# Generated by Django 5.2.5 on 2025-08-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipoHabitacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
