# Generated by Django 5.2.6 on 2025-09-22 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_habitacion_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='alojamiento',
            old_name='user_id',
            new_name='propietario',
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='usuario',
            new_name='propietario',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='identificacion',
            new_name='dni_huesped',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombreHuesped',
        ),
        migrations.AddField(
            model_name='reserva',
            name='huesped',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
