# Generated by Django 5.2.6 on 2025-09-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_user_id_alojamiento_propietario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='alojamiento_id',
            new_name='alojamiento',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='reserva_id',
            new_name='reserva',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='propietario',
        ),
    ]
