# Generated by Django 5.2.6 on 2025-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_alojamiento_id_habitacion_alojamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='checkIn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
