# Generated by Django 5.2.6 on 2025-09-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_reserva_checkin_alter_reserva_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='nombre_huesped',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
