# Generated by Django 5.2.6 on 2025-10-04 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_reserva_nombre_huesped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen',
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.habitacion')),
            ],
        ),
    ]
