# Generated by Django 5.2.6 on 2025-10-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_habitacion_imagen_fotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='bañoPrivado',
            new_name='banoPrivado',
        ),
    ]
