# Generated by Django 5.2.6 on 2025-10-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_bañoprivado_habitacion_banoprivado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='dni_huesped',
            new_name='dniHuesped',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='nombre_huesped',
            new_name='nombreHuesped',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantHuespedes',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
