# Generated by Django 5.2.6 on 2025-10-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_dni_huesped_reserva_dnihuesped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='tipoHabitacion',
        ),
    ]
